/*
 * Copyright 2015 TheShark34
 *
 * This file is part of the OpenLauncherLib.

 * The OpenLauncherLib is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * The OpenLauncherLib is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with the OpenLauncherLib.  If not, see <http://www.gnu.org/licenses/>.
 */
package fr.theshark34.openlauncherlib.util;

import fr.theshark34.openlauncherlib.FailException;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileWriter;
import java.util.Properties;

/**
 * The Saver
 *
 * <p>
 *     Save some things to a file.
 * </p>
 *
 * @author TheShark34
 * @version 3.0.0-SNAPSHOT
 */
public class Saver
{
    /**
     * The file where to save the things
     */
    private File file;

    /**
     * The properties object
     */
    private Properties properties;

    /**
     * The Saver
     *
     * @param file The file where to save the things
     */
    public Saver(File file)
    {
        this.file = file;
        this.properties = new Properties();

        if (file.exists())
            load();
    }

    /**
     * Set something
     *
     * @param key   The key
     * @param value The value
     */
    public void set(String key, String value)
    {
        properties.setProperty(key, value);
        save();
    }

    /**
     * Loads something
     *
     * @param key The key of the thing to get
     *
     * @return The value if founded, or null
     */
    public String get(String key)
    {
        return properties.getProperty(key);
    }

    /**
     * Loads somethings with a default value
     *
     * @param key The key of the thing to get
     * @param def The default value
     *
     * @return The value if founded, or the def if not
     */
    public String get(String key, String def)
    {
        String value = properties.getProperty(key);
        return value == null ? def : value;
    }

    /**
     * Save the properties (automatic when you do {@link #set(String, String)})
     */
    public void save()
    {
        try
        {
            properties.store(new BufferedWriter(new FileWriter(file)), "Generated by the OpenLauncherLib Saver");
        }
        catch (Throwable t)
        {
            throw new FailException("Can't save the properties", t);
        }
    }

    /**
     * Load the properties (automatic when you do {@link #Saver(File)}
     */
    public void load()
    {
        try
        {
            properties.load(new FileInputStream(file));
        }
        catch (Throwable t)
        {
            throw new FailException("Can't load the properties", t);
        }
    }
}
